<?php
global $wpt_actions;

/**
 * All actions list
 * @var array
 */
$wpt_actions = array(
	'rest-api' =>  array(
		'label'			=> __( 'Deactivate REST-API', WPT_LG ),
		'description'	=> __( '', WPT_LG ),
		'section'		=> 'security',
		'type'			=> 'checkbox',
		'cb'			=> 'wptunning_deactivate_rest_api',
		'args'			=> '',
	),
	'connection_error' => array(
		'label'			=> __( 'Hide connection error', WPT_LG ),
		'description'	=> __( 'Hide connection error information in <code>wp-login.php</code>', WPT_LG ),
		'section'		=> 'security',
		'type'			=> 'checkbox',
		'cb'			=> 'wptunning_deactivate_connection_error_wplogin',
		'args'			=> '',
	),
	'deactivate_author' => array(
		'label'			=> __( 'Deactivate author page and author link', WPT_LG ),
		'description'	=> __( '', WPT_LG ),
		'section'		=> 'security',
		'type'			=> 'checkbox',
		'cb'			=> 'wptunning_deactivate_author_page_and_link',
		'args'			=> '',
	),
	'protect_media_filename' => array(
		'label'			=> __( 'No punctuation and accents for uploaded file', WPT_LG ),
		'description'	=> __( '', WPT_LG ),
		'section'		=> 'media',
		'type'			=> 'checkbox',
		'cb'			=> 'wptunning_protect_media_filename',
		'args'			=> ''/*array( 'class' => 'meme' )*/
	),
	'add_medium_large' => array(
		'label'			=> __( 'Add format <em>Medium Large</em>', WPT_LG ),
		'description'	=> __( 'Display the existent default format <em>Medium Large</em> (768px) when you choose a media in a post', WPT_LG ),
		'section'		=> 'media',
		'type'			=> 'checkbox',
		'cb'			=> 'wptunning_add_medium_large',
		'args'			=> '',
	),
	'remove_default_dashboard_widgets' => array(
		'label'			=> __( 'Clean dashboard', WPT_LG ),
		'description'	=> __( 'Deactivate the default widget (<em>welcome panel</em>, <em>Activity</em>, <em>Quick Draft</em>, <em>WordPress Events and News</em>)  in admin dashboard', WPT_LG ),
		'section'		=> 'misc',
		'type'			=> 'checkbox',
		'cb'			=> 'wptunning_remove_default_dashboard_widgets',
		'args'			=> '',
	),
	'disallow_file_edit' => array(
		'label'			=> __( 'Disallow file editor', WPT_LG ),
		'description'	=> __( 'Disallow file editor for plugins and themes in wp-admin.', WPT_LG ),
		'section'		=> 'misc',
		'type'			=> 'checkbox',
		'cb'			=> 'wptunning_disallow_file_edit',
		'args'			=> '',
	),
	'disable_emojis' => array(
		'label'			=> __( 'Disabled emoji', WPT_LG ),
		'description'	=> __( 'Reduces resources number loaded on front page', WPT_LG ),
		'section'		=> 'misc',
		'type'			=> 'checkbox',
		'cb'			=> 'wptunning_disable_emojis',
		'args'			=> '',
	),
	'deactivate_H1' => array(
		'label'			=> __( 'Remove H1 in Tiny MCE', WPT_LG ),
		'description'	=> __( '<em>H1</em> should never be used in the editor', WPT_LG ),
		'section'		=> 'misc',
		'type'			=> 'checkbox',
		'cb'			=> 'wptunning_deactivate_H1',
		'args'			=> '',
	),
	'define_post_revision' => array(
		'label'			=> __( 'Number max of revisions', WPT_LG ),
		'description'	=> __( 'Define the number of revisions you want that WordPress saved. (Leave blank for unlimited)', WPT_LG ),
		'section'		=> 'misc',
		'type'			=> 'text',
		'cb'			=> 'wptunning_define_post_revision',
		'args'			=> '',
	),
	'wp_generator' => array(
		'label'			=> __( 'Remove WordPress version', WPT_LG ),
		'description'	=> __( 'Remove the generator tag that is generated', WPT_LG ),
		'section'		=> 'head',
		'type'			=> 'checkbox',
		'cb'			=> 'wptunning_wp_generator',
		'args'			=> '',
	),
	'wlwmanifest_link' => array(
		'label'			=> __( 'Remove Windows Live Writer Manifest', WPT_LG ),
		'description'	=> __( 'Remove Windows Live Writer Manifest Link.', WPT_LG ),
		'section'		=> 'head',
		'type'			=> 'checkbox',
		'cb'			=> 'wptunning_wlwmanifest_link',
		'args'			=> '',
	),
	/*'rsd_link' => array(
		'label'			=> 'Deactivate RSD',
		'description'	=> 'Deactivate Display the link to the Really Simple Discovery service endpoint',
		'section'		=> 'head',
		'type'			=> 'checkbox',
		'cb'			=> 'wptunning_rsd_link',
		'args'			=> '',
	),
	'xmlrpc_enabled' => array(
		'label'			=> 'Deactivate XML-RPC',
		'description'	=> 'Deactivate XML-RPC methods requiring authentication are enabled.',
		'section'		=> 'head',
		'type'			=> 'checkbox',
		'cb'			=> 'wptunning_xmlrpc_enabled',
		'args'			=> '',
	),*/
	'xmlrpc_enabled_rsd' => array(
		'label'			=> __( 'Deactivate XML-RPC', WPT_LG ),
		'description'	=> __( 'Deactivate XML-RPC methods requiring authentication are enabled.', WPT_LG ),
		'section'		=> 'head',
		'type'			=> 'checkbox',
		'cb'			=> 'wptunning_xmlrpc_enabled_rsd',
		'args'			=> '',
	),
	'feed_links' => array(
		'label'			=> __( 'Remove RSS feed', WPT_LG ),
		'description'	=> __( '', WPT_LG ),
		'section'		=> 'head',
		'type'			=> 'checkbox',
		'cb'			=> 'wptunning_feed_link',
		'args'			=> '',
	),
	'feed_links_extra' => array(
		'label'			=> __( 'Remove Comment RSS feed', WPT_LG ),
		'description'	=> __( '', WPT_LG ),
		'section'		=> 'head',
		'type'			=> 'checkbox',
		'cb'			=> 'wptunning_comments_feed',
		'args'			=> '',
	),
	/***
	'start_post_rel_link' => array(
		'label'			=> '',
		'description'	=> '',
		'section'		=> 'head',
		'type'			=> 'checkbox',
		'cb'			=> 'wptunning_start_post_rel_link',
		'args'			=>'',
	),
	'wp_shortlink_wp_head' => array(
		'label'			=> '',
		'description'	=> '',
		'section'		=> 'head',
		'type'			=> 'checkbox',
		'cb'			=> 'wptunning_wp_shortlink_wp_head',
		'args'			=>'',
	),
	'index_rel_link' => array(
		'label'			=> '',
		'description'	=> '',
		'section'		=> 'head',
		'type'			=> 'checkbox',
		'cb'			=> 'wptunning_index_rel_link',
		'args'			=>'',
	),
	'parent_post_rel_link' => array(
		'label'			=> '',
		'description'	=> '',
		'section'		=> 'head',
		'type'			=> 'checkbox',
		'cb'			=> 'wptunning_parent_post_rel_link',
		'args'			=>'',
	),
	*/
); // end $wpt_actions
